#! /bin/bash

sudo apt-get update
wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
sudo dpkg --install chrome-remote-desktop_current_amd64.deb
sudo apt install --assume-yes --fix-broken
sudo DEBIAN_FRONTEND=noninteractive \
#apt install --assume-yes xfce4 desktop-base
sudo DEBIAN_FRONTEND=noninteractive apt install --assume-yes xfce4 desktop-base keyboard-configuration console-data \
    -o Dpkg::Options::="--force-confdef" \
    -o Dpkg::Options::="--force-confold"

sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'  
sudo apt install --assume-yes xscreensaver
sudo systemctl disable lightdm.service
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg --install google-chrome-stable_current_amd64.deb
sudo apt install --assume-yes --fix-broken
sudo apt install nautilus nano -y
sudo apt install xfce4-terminal -y



read -p "what is your username : " username
read -p "what is your password : " passwd
printf '\nCheck https://remotedesktop.google.com/headless  Copy Command Of Debian Linux And Paste Down\n'
read -p "Paste Here: " CRP
read -p "what is your pin : " pin
printf "This script modify by Aung Myo Zaw.This is not my script crd to owner wait for download \n " >&2
{
sudo useradd -m $username
sudo adduser $username sudo
printf "$username:$passwd" | sudo chpasswd
sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd

sudo adduser $username chrome-remote-desktop
} &> /dev/null &&
printf "\nSetup Completed " >&2 ||
printf "\nError Occured " >&2
printf "$pin\n$pin" | su - $username -c """$CRP"""
printf 'Check https://remotedesktop.google.com/access/ \n'
printf 'This is my account www.facebook.com/aungmyozaw123 \n'
service chrome-remote-desktop restart
sudo apt update
sudo apt install dbus-x11
eval $(dbus-launch --sh-syntax)
export DBUS_SESSION_BUS_ADDRESS
dbus-launch --exit-with-session startxfce4
service chrome-remote-desktop stop
service chrome-remote-desktop start
